version: '3'

services: 

  app:
    build: 
      context: node
    container_name: app
    tty: true
    entrypoint: ["sh", "entrypoint.sh"]
    volumes: 
      - ./node:/usr/src/app
    networks: 
      - node-network
    depends_on: 
       - db

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes: 
      - ./mysql:/var/lib/mysql
    environment: 
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks: 
      - node-network

  nginx:
    build: 
      context: nginx
    ports:
      - "8080:80"
    networks:
      - node-network
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    # depends_on:
    #   - app


networks: 
  node-network:
    driver: bridge  
